name: Push Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
           server_address: smtp.gmail.com
           server_port: 465
           from: ${{ secrets.EMAIL }}
           to: ${{ secrets.EMAIL }}
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "Push Notification"
           body: "Push Notification"
        

 
            
        